platform:ios, '9.0'
use_frameworks!
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

target 'ZJSAlertViewDemo' do
  
pod 'Masonry' 
    
end







